version: '3'
services:

  # Nodejs
  dashboard-queue:
    image: dashboard-queue
    container_name: dashboard-queue
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - .:/usr/apps/jds/express-dashboard-queue
      - /usr/apps/jds/express-dashboard-queue/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"

#Docker Networks
networks:
  default:
    external:
      name: crowdsource-api-network
